### PR TITLE
Jenkins

### PR DESCRIPTION
**Pull request by wherkamp**
Changes KLauncher to download the engine and kakara via the Jenkins API.

### CODE REVIEW

**Comment by wherkamp** [comment]
Features to add 
- [ ] Param Value --game jenkins:{branch}
- [ ] Param Value --engine jenkins:{branch}

**Comment by wherkamp** [comment]
All I want to do is improve the download code to be more readable and logical.

**Comment by wherkamp** [comment]
image

**Review by ryandw11 — APPROVED** [review]
Looks good.

**Pull request merged**
